[alembic]
script_location = alembic

[loggers]
keys = root,alembic

[logger_root]
level = WARN
handlers = console

[logger_alembic]
level = INFO
handlers = console
qualname = alembic

[handlers]
keys = console

[handler_console]
class = StreamHandler
args = (sys.stderr,)
formatter = generic

[formatters]
keys = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
